### ISSUE TITLE
Charmap.txt

### ISSUE THREAD

**Issue by adekmzrk** [andrew98450/PassGAN#1]
where are the charmap.txt file? i cannot find that file in entire web. please answer, thank you

**Comment by head790** [comment]
> where are the charmap.txt file? i cannot find that file in entire web. please answer, thank you

did you found charmap.txt?

**Comment by andrew98450** [comment]
charmap.txt and PassGAN.ipynb has been uploaded.

**Comment by head790** [comment]
> charmap.txt and PassGAN.ipynb has been uploaded.

new charmap file dont work with current code
